### ISSUE TITLE
Your twitch downloader is perfect!!

### ISSUE THREAD

**Issue by rmfkdehd** [swent/twitch-unjail#1]
Hello, your twitch video downloader went very fast.
I have a personal suggestion for you.

The downloader's progress seemed to be updated horizontally.
Could you please allow it to be updated vertically?

Thank you for making such a great program!

**Comment by rmfkdehd** [comment]
Now that I think about it, it doesn't seem bad to update the progress horizontally. (Some words don't seem to be updated due to my cli problem.

**Comment by swent** [comment]
Hey, thanks for the kind words, I really tried to get fast download speeds so I'm happy its working for you.

Yes I played around with the progress update screen but sadly just printing all the text again and again results in flickering of the text, so instead I went for a very common thing: just overwriting parts of the texts that changed.
Unfortunatly this is very error prone and breaks (or looks broken) when the lines/positions don't match up with how its intended to display.

I will try to find a better solution, could you maybe send me a screenshot of how it's displaying for you? Also would be nice to know the terminal app / OS you are using so I can further check.

**Comment by rmfkdehd** [comment]
I first used the web cli. But I used ssh from ubuntu cli and it worked perfectly. This was a cli issue.
